# Generated by Django 4.2.7 on 2025-10-06 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='emails.emailaccount'),
        ),
        migrations.AlterUniqueTogether(
            name='emailaccount',
            unique_together={('user', 'email_address')},
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['-received_at'], name='emails_receive_c92fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['importance'], name='emails_importa_a19a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['is_read'], name='emails_is_read_7adf55_idx'),
        ),
    ]
