# Generated by Django 4.2.7 on 2025-10-08 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('sender', 'Sender Email'), ('keyword', 'Keyword in Subject/Body'), ('subject', 'Subject Contains'), ('body', 'Body Contains'), ('attachment', 'Has Attachment'), ('reply', 'Is a Reply/Forward'), ('ai', 'AI Context Rule')], max_length=50)),
                ('value', models.TextField(blank=True, help_text='Email, keyword(s), or pattern depending on rule type', null=True)),
                ('importance', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Email Rule',
                'verbose_name_plural': 'User Email Rules',
                'ordering': ['-created_at'],
            },
        ),
    ]
