# Generated by Django 4.2.7 on 2025-10-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_useremailrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='embedding_generated',
            field=models.BooleanField(default=False),
        ),
    ]
