# Generated by Django 4.2.7 on 2025-10-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0004_email_embedding_email_embedding_generated"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="body_html",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="email",
            name="sender_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
