# Generated by Django 4.2.7 on 2025-10-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_email_body_html_email_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='channel',
            field=models.CharField(default='email', max_length=50),
        ),
    ]
