# Generated by Django 4.2.7 on 2025-10-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ai_next_step',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='ai_organizations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='ai_people',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='ai_related',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
