# Generated by Django 4.2.7 on 2025-10-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0002_message_ai_next_step_message_ai_organizations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='ai_organizations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='ai_related',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
