# Generated by Django 4.2.7 on 2025-10-24 08:05

from django.db import migrations
import unified.models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0004_alter_message_ai_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelaccount',
            name='access_token',
            field=unified.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channelaccount',
            name='refresh_token',
            field=unified.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='actionable_data',
            field=unified.models.EncryptedJSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='next_step_suggestion',
            field=unified.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='people_and_orgs',
            field=unified.models.EncryptedJSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='summary',
            field=unified.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='ai_next_step',
            field=unified.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='ai_organizations',
            field=unified.models.EncryptedJSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='ai_people',
            field=unified.models.EncryptedJSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='ai_related',
            field=unified.models.EncryptedJSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='ai_summary',
            field=unified.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachments',
            field=unified.models.EncryptedJSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=unified.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='importance_analysis',
            field=unified.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='metadata',
            field=unified.models.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipients',
            field=unified.models.EncryptedJSONField(blank=True, default=list),
        ),
    ]
