# Generated by Django 4.2.7 on 2025-11-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("unified", "0005_alter_channelaccount_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelaccount",
            name="last_history_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
