# Generated by Django 4.2.7 on 2025-10-08 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistant', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('default_model', models.CharField(default='gpt-4', max_length=100)),
                ('max_response_length', models.IntegerField(default=500)),
                ('temperature', models.FloatField(default=0.7)),
                ('top_p', models.FloatField(default=1.0)),
                ('frequency_penalty', models.FloatField(default=0.0)),
                ('presence_penalty', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_configs',
                'unique_together': {('user',)},
            },
        ),
    ]
