# Generated by Django 4.2.7 on 2025-10-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_assistantconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistantconfig',
            name='frequency_penalty',
        ),
        migrations.RemoveField(
            model_name='assistantconfig',
            name='presence_penalty',
        ),
        migrations.AddField(
            model_name='assistantconfig',
            name='custom_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistantconfig',
            name='tone',
            field=models.CharField(default='professional', max_length=50),
        ),
    ]
