# Generated by Django 4.2.7 on 2025-10-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_assistantmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistanttask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistanttask',
            name='due_time',
            field=models.DateTimeField(blank=True, help_text='Time to trigger the task', null=True),
        ),
        migrations.AddField(
            model_name='assistanttask',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assistanttask',
            name='recurrence_pattern',
            field=models.CharField(blank=True, help_text='e.g., daily, weekly, every Monday', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assistanttask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='assistanttask',
            name='task_type',
            field=models.CharField(choices=[('reply', 'Generate Reply'), ('summarize', 'Summarize'), ('translate', 'Translate'), ('analyze', 'Analyze'), ('reminder', 'Reminder'), ('email_send', 'Send Email')], max_length=30),
        ),
    ]
