# Generated by Django 4.2.7 on 2025-10-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_assistanttask_due_date_assistanttask_due_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistanttask',
            old_name='due_time',
            new_name='due_datetime',
        ),
        migrations.RemoveField(
            model_name='assistanttask',
            name='due_date',
        ),
        migrations.AddField(
            model_name='assistanttask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
